
services: 
  web:
    build: .
    container_name: auth_web_app
    ports:
      - "8000:8000"
    volumes:
      - "./app/:/code/app"
    environment:
      - ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: auth_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: